# Date sync setup
---
- hosts: all

  tasks:
    - name: setup timezone
      command: "timedatectl set-timezone America/New_York"

    - name: start chrony
      service: name=chronyd state=started enabled=yes
