---
- hosts: rhel_hosts,fedora_hosts
  tasks:
  - name: cockpit
    yum:
      name:
        - cockpit
        - cockpit-dashboard
        - cockpit-ws
        - cockpit-packagekit
        - cockpit-storaged
        - cockpit-composer
        - cockpit-system
        - cockpit-pcp
        - cockpit-bridge
      state: latest

  - name: cockpit service socket
    service:
      name: cockpit.socket
      state: started
      enabled: true

  - name: cockpit store metrics
    service:
      name: pmlogger.service
      state: started
      enabled: true

- hosts: rhel_hosts
  tasks:
  - name: cockpit on RHEL
    yum:
      name:
        - subscription-manager-cockpit

  - name: cockpit on RHEL8
    yum:
      name:
        - cockpit-session-recording
    when: ansible_distribution_major_version|int >=8

- hosts: fedora_hosts
  tasks:
  - name: cockpit on Fedora
    yum:
      name:
#        - cockpit-machines-ovirt
        - cockpit-podman
        - cockpit-session-recording

- hosts: kvm_hosts
  tasks:
  - name: cockpit VM management
    yum:
      name:
        - cockpit-machines
      state: latest
...
