---
- hosts: rhel_hosts,fedora_hosts
  tasks:
  - name: cockpit main packages
    yum:
      name:
        - cockpit
        - cockpit-dashboard
        - cockpit-ws
        - cockpit-packagekit
        - cockpit-storaged
        - cockpit-composer
        - cockpit-system
        - cockpit-pcp
        - cockpit-bridge
      state: latest

  - name: cockpit service socket
    service:
      name: cockpit.socket
      state: started
      enabled: true

  - name: cockpit store metrics
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
    - pmcd
    - pmlogger

- hosts: rhel_hosts
  tasks:
  - name: cockpit on RHEL packages
    yum:
      name:
        - subscription-manager-cockpit

  - name: cockpit on RHEL8 packages
    yum:
      name:
        - cockpit-session-recording
    when: ansible_distribution_major_version|int >=8

- hosts: fedora_hosts
  tasks:
  - name: cockpit on Fedora packages
    yum:
      name:
#        - cockpit-machines-ovirt
        - cockpit-podman
        - cockpit-session-recording

- hosts: kvm_hosts
  tasks:
  - name: cockpit VM management packages
    yum:
      name:
        - cockpit-machines
      state: latest

- hosts: ubuntu_hosts
  tasks:
  - name: cockpit package
    apt:
      name:
        - cockpit
      state: latest
...