---
- hosts: rhel_hosts,fedora_hosts

  tasks:
  - name: packages for ebpf
    yum:
      name:
        - bcc
        - bcc-tools
        - kernel-devel
      state: latest

  - name: rhel7 package
    yum:
      name:
        - python-bcc
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int < 8

  - name: fedora and rhel8+ package
    yum:
      name:
        - python3-bcc
    when: ansible_distribution == 'Fedora' or (ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8)
...
