---
- hosts: rhel_hosts,fedora_hosts

  tasks:
  - name: packages for ebpf
    yum:
      name:
        - bcc
        - bcc-tools
        - kernel-devel
      state: latest

  - name: rhel7 package
    yum:
      name:
        - python-bcc 
    when: (ansible_facts[‘distribution’] == RedHat && ansible_facts[‘distribution_major_version’]|int == 7)

  - name: rhel8+ package
    yum:
      name:
        - python3-bcc
    when: (ansible_facts[‘distribution’] == Fedora || (ansible_facts[‘distribution’] == RedHat && ansible_facts[‘distribution_major_version’]|int >= 8))
...
