---
- hosts: all

  tasks:
  - name: git packages
    yum: name={{ item }} state=latest
    with_items:
      - git

- hosts: desktops
  tasks:
  - name: git interface
    yum: name={{ item }} state=latest
    with_items:
      - git-cola

