---
- hosts: all

  tasks:
  - name: monitoring packages
    yum: name={{ item }} state=latest
    with_items:
      - lm_sensors
      - hddtemp

- hosts: desktops

  tasks:
  - name: kde monitors
    yum: name={{ item }} state=latest
    with_items:
      - ksysguard

