---
- hosts: icinga

  vars:
    selinux_policy_drop_dir: /tmp/selinux_ansible_drop

  tasks:
#############################################
  - name: check for pkg repository
    stat: path=/etc/yum.repos.d/ICINGA-release.repo
    register: yumrepo

#############################################
  - name: add pkg repository if missing
    get_url: url=http://packages.icinga.org/epel/ICINGA-release.repo \
             dest=/etc/yum.repos.d/ICINGA-release.repo
    when: yumrepo.stat.exists == false

#############################################
  - name: mysql packages
    yum: name={{ item }} state=latest
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python

#############################################
  - name: icinga packages
    yum: name={{ item }} state=latest
    with_items:
      - icinga2
      - nagios-plugins-all
      - icinga2-ido-mysql
      - icingaweb2
      - icingacli

#############################################
  - name: icinga db
    mysql_db: name=icinga state=present
              login_user=root login_password={{ mysql_root_password }}
    notify: create-icinga-db

#############################################
  - name: icinga user
    mysql_user: name=icinga state=present password={{ icinga_db_password }}
                append_privs=yes
                login_user=root login_password={{ mysql_root_password }}
                priv='icinga.*:SELECT,INSERT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE'

#############################################
  - name: store MySQL login parms for icinga
    lineinfile:
      dest=/etc/icinga2/features-available/ido-mysql.conf
      regexp='^\s*password\s*=\s*"'
      line='   password = "{{ icinga_db_password }}"' 
      insertafter="^.*IdoMysqlConnection.*{"
# '
    notify: reload-icinga

#############################################
  - name: PHP default timezone
    lineinfile: dest=/etc/php.ini regexp="^\s*date.timezone=" line="date.timezone=America/New_York" insertafter="^;date.timezone"

#############################################
  - name: Turn off SELinux for httpd - icingaweb2 cant hack it
    command: semanage permissive -a httpd_t

#############################################
  - name: copy http root index file
    copy: dest=/var/www/html/index.html src=index.html force=no

#############################################
  - name: insert icinga link in http index file
    lineinfile:
      dest=/var/www/html/index.html
      regexp="/icingaweb2/"
      line="<li><a href="/icingaweb2/">Icinga Monitoring</a></li>"
      insertafter="<ul>"

#############################################
  - name: enable services
    service: name={{ item }} enabled=yes state=started
    with_items:
    - httpd
    - mariadb
    - icinga2

#############################################
  - name: Gather icinga2 enabled features
    command: icinga2 feature list
    register: icinga2feat

#############################################
  - name: Enable ido-mysql feature
    command: icinga2 feature enable command
    when:  "{{ icinga2feat.stdout | search('Disabled features:.* ido-mysql.*\n') }}"
    notify: restart-icinga

#############################################
  - name: Enable command feature
    command: icinga2 feature enable command
    when:  "{{ icinga2feat.stdout | search('Disabled features:.* command.*\n') }}"
    notify: restart-icinga

#############################################
  handlers:
    - name: create-icinga-db
      mysql_db: name=icinga
                login_password={{ mysql_root_password }} login_user=root
                state=import target=/usr/share/icinga2-ido-mysql/schema/mysql.sql

#############################################
    - name: restart-icinga
      service: name=icinga2 state=restarted

#############################################
    - name: reload-icinga
      service: name=icinga2 state=reloaded

#############################################
    - name: reload-httpd
      service: name=httpd state=reloaded
