---
- hosts: kvm_hosts

  tasks:
  - name: Virt packages
    yum: name={{ item }} state=latest
    with_items:
      - qemu-kvm 
      - libvirt
      - virt-install
      - bridge-utils

  - name: polikit permission
    copy:
      dest: /etc/polkit-1/rules.d/50-libvirt.rules
      src: kvm/50-libvirt.rules
      backup: yes
      mode: "u=rw,g=r,o=r"
      owner: root
      group: root

  - name: add user to libvirt and wheel group 
    # libvirt lets them manage virt stuff per above policy
    # wheel is needed to sudo and change permissions on files to use chmod on virsh created qcow files
    user:
      name:   pladd
      groups: libvirt,wheel
      append: yes

...
