---
- name: beast_libvirt_setup
  hosts: beast
  roles:
    - role: stackhpc.libvirt-host
      libvirt_host_pools:
        - name: data_fast
          type: dir
          path: /data/libvirt_images
          owner: qemu
          group: qemu
          mode: 775
        - name: libvirt_images
          type: dir
          path: /var/lib/libvirt/images
          owner: qemu
          group: qemu
          mode: 775
        - name: libvirt_isos
          type: dir
          path: /var/lib/libvirt/images/isos
          owner: qemu
          group: qemu
          mode: 775
...