---
- name: basic setup for OCP hosts
  hosts: ocp_masters
  vars_files:
    - subscription-manager-local.vault

  tasks:
  - name: subscribe system
    redhat_subscription:
      username: "{{ subscription_manager_id }}"
      password: "{{ subscription_manager_pw }}"
      environment: Library
      pool_ids:
        - 4028fa5565165fc001651f55104d04a9 # RHEL Guest
        - 4028fa5565165fc001651f5b32a1051a # Ansible
        - 4028fa5563f6ca6d0163f71ef12c0958 # OCP

  - name: Disable all RHSM repositories
    rhsm_repository:
      name: '*'
      state: disabled

  - name: repositories
    rhsm_repository:
      name:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ose-3.9-rpms
        - rhel-7-fast-datapath-rpms
        - rhel-7-server-ansible-2.4-rpms
        - rhel-7-server-satellite-tools-6.3-rpms
      state: enabled

  - name: package installation
    yum:
      name:
        - wget
        - git
        - net-tools 
        - bind-utils
        - yum-utils
        - iptables-services 
        - bridge-utils 
        - bash-completion 
        - kexec-tools 
        - sos 
        - psacct
        - atomic-openshift-utils
        - docker-1.13.1
      state: latest

  - name: docker lv
    lvol:
      lv: docker-lv 
      vg: rhel
      size: 20G

  - name: config for docker-storage
    lineinfile:
      dest: /etc/sysconfig/docker-storage-setup
      line: "{{ item }}"
    with_items:
      - "DEVS=/dev/vdc"
      - "VG=docker-vg"

...
