---
- hosts: all

  tasks:
  - name: upgrade all packages
    package: name=* state=latest
  - name: useful packages
    package: name={{ item }} state=latest
    with_items:
      - net-tools
      - vim
      - ntpdate
      - lsof
      - bash-completion
      - libselinux-python # needed for lots of ansible scripts

- hosts: desktops

  tasks:
  - name: desktop utility
    package: name={{ item }} state=latest
    with_items:
      - network-manager-applet

