---
- hosts: rhel_hosts

  tasks:
  - name: useful packages
    yum:
      name:
        - net-tools
        - vim
        - ntpdate
        - lsof
        - bash-completion
        - libselinux-python # needed for lots of ansible scripts
        - tree
        # monitoring tools
        - iotop
        - dstat
#        - nmon   # needs EPEL
      state: latest

- hosts: desktops

  tasks:
  - name: desktop utility
    package: name={{ item }} state=latest
    with_items:
      - network-manager-applet

