---
- hosts: rhel_hosts

  tasks:
  - name: useful_packages
    yum:
      name:
        - bash-completion
        - pciutils
        - unzip
        - vim
        - wget
        - numactl
        - sos
        - ansible
        - iotop
        - procps-ng
        - net-tools
        - nmap
        - tcpdump
        - traceroute
        - wireshark
        - bind-utils # for dig
        - rsync
#        - ntpdate
        - lsof
#        - libselinux-python # needed for lots of ansible scripts
        - tree
        - dstat
      state: latest

  - name: copy_top_config
    copy:
      src: toprc
      dest: /root/.toprc

- hosts: desktops

  tasks:
  - name: desktop utility
    package: name={{ item }} state=latest
    with_items:
      - network-manager-applet
      - baobab

