# Red Hat Virtualization
---
- hosts: rhv_hosts

  tasks:
  - name: RHV_repositories
    rhsm_repository:
      name:
        - rhel-7-server-rhv-4.3-manager-rpms
        - rhel-7-server-rhv-4-manager-tools-rpms
        - rhel-7-server-ansible-2-rpms
        - jb-eap-7.2-for-rhel-7-server-rpms
      state: enabled

  - name: rhv packages
    yum:
      name: rhvm

...
