---
- name: sat6 deployment
  hosts: sat6

  tasks:

  - name: repositories
    rhsm_repository:
      name:
      - rhel-7-server-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-satellite-6.6-rpms
      - rhel-7-server-satellite-maintenance-6-rpms
      - rhel-7-server-ansible-2.8-rpms
      state: enabled
      purge: yes

  - name: install_sat6
    yum:
      name: satellite

  - name: copy_config
    copy:
      src: sat6/satellite-answers.yaml
      dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml

  # had to follow this to make it work... https://access.redhat.com/solutions/3497301

  - name: configure_satellite
    command: 'satellite-installer --scenario satellite'
    register: sat_config

  - name: config_output
    debug:
      var: sat_config

...
