---
- hosts: desktops
  tasks:

  - name: steam repo
    get_url:
      url: https://negativo17.org/repos/fedora-steam.repo
      dest: /etc/yum.repos.d/

  - name: install steam
    package: name=steam state=latest
